### ISSUE TITLE
Searching text "phone" inside a project

### ISSUE THREAD

**Issue by harikt** [rxi/lite#89] opened 2020-05-12 11:12 UTC
Hi,

First I would like to thank you for open-sourcing such a wonderful project. Thank you.

An issue I noticed on testing the 1.03 version.

I searched in project level and it works. But when I searched text `phone` lite crashes and throws 

`Fatal error in src/rencache.c: exhausted command buffer`

When looking at code I noticed the error was thrown from https://github.com/rxi/lite/blob/23cf193026014a9d720e9690979299eb513f980e/src/rencache.c#L83

Is there a way we can increase this buffer size something similar to LITE_SCALE ?

Thank you once again for the beautiful project.

**Comment by rxi** [comment] 2020-05-12 11:28
I'm assuming this was in a file with with long lines, if so this issue is a duplicate of #64

**Comment by harikt** [comment] 2020-05-12 13:05
ok. I am not sure this was in a file with long lines for I cannot debug it. Is there a way we can understand this happened on `X` file / line ?

**Comment by rxi** [comment] 2020-05-13 10:06
I'm a little confused how you don't know if the file you were searching had long lines or not. Without any more information I'm just going to assume this is the same issue as the one I mentioned above.

**Closed by rxi** 2020-05-13 10:06 UTC

**Comment by harikt** [comment] 2020-05-14 04:07
@rxi there are multiple files in the project. Some of them are js files. So it may be having long lines. But I am not sure which file is causing the issue for the error doesn't mention this happened in X file or I can see a log to check what happened for the failure. 

I also guess this is same as the one you mentioned. But I cannot gaurantee that it is right for the current time. I can open if the issue you mentioned has been fixed and same error happened after that.

Question : Is there a way we can see more log? I noticed plugin loaded etc. But not anything like error happened at this line after search.

**Comment by rxi** [comment] 2020-05-14 07:03
>  I can open if the issue you mentioned has been fixed and same error happened after that.

That sounds like the best approach.

> Is there a way we can see more log? I noticed plugin loaded etc. But not anything like error happened at this line after search.

This issue happens on the C layer, for those kinds of errors there isn't a way of propagating more information to the UI the way unhandled lua errors do -- for example, the errors you'd encounter when developing a plugin would be logged to the UI with a traceback. Luckily the C layer specific to lite is small enough that there are few points of failure -- this is the only crash on this level I've experienced and I already have an idea of why it's happening and how to approach fixing it; these aren't errors that should be popping up frequently.

**Comment by harikt** [comment] 2020-05-14 18:05
This looks fixed to some extend. Currently it logs the error to terminal. But good for now.
