### ISSUE TITLE
High idle utilization

### ISSUE THREAD

**Issue by kennylevinsen** [rxi/lite#73] opened 2020-05-10 17:14 UTC
Under both X11 and Wayland, I see ~2% idle CPU usage from simply having a file open, without cursor focus and thus no ongoing animations or rendering.

I would expect a rock-solid 0% in this scenario. I have not looked into what is causing the wakeups.

(Note: Target machine is an ultrabook that tends to run at 800MHz, which amplifies these types of idle/background drains.)

**Comment by nico-abram** [comment] 2020-05-10 17:27
On windows for me just opening the sqlite3 amalgamation C file (its like 204k LoC) with lite open on a decently sized C++ project cpu usage oscilates between 0.2% and 25% (On an i5 haswell cpu) with lite idle in the background (Not the active window). Memory usage also seems to be climbing steadily with it on the background like that

**Comment by rxi** [comment] 2020-05-10 18:17
@kennylevinsen I agree this isn't ideal and something I'll look into

@nico-abram Does this happen with no files open? Would you be able to let me know how many files it reports the project having? (If you close all the views or press `ctrl+shift+p` it will say it in the bottom right)

**Comment by nico-abram** [comment] 2020-05-10 18:40
https://i.imgur.com/t981slq.png
48278 files (This includes third party libs like pcre, zlib, stb, discord rpc, ffmpeg, luajit, sqlite and sqlitecpp, fftw, libcurl, libmad, tomcrypt, newvorbis and newogg, rapidjson, websocketpp, etc)

You're right, it happens even with no files open. Is it the project/file scanning?

**Comment by rxi** [comment] 2020-05-10 18:50
I believe this may be the case given the number of files; presumably setting `config.project_scan_rate` to  `30` would cause the spike to happen less frequently and confirm this to be the cause.

**Comment by nico-abram** [comment] 2020-05-10 19:04
I just made it only do the scan at startup and that completely removed both the memory increase and the cpu usage, so yes, it's that

**Comment by rxi** [comment] 2020-05-11 12:27
@kennylevinsen I've pushed a commit which should lower idle CPU usage when the window isn't focused: c215eff6d8b1774ac214a96b2ba2370b4474b60b

@nico-abram the project-scan-with-many-files problem is separate to the original issue in this thread, but is certainly not ideal behaviour; feel free to open an issue specifically for this problem and then I can close this one, thanks!

**Comment by kennylevinsen** [comment] 2020-05-11 14:42
Hmm, the linked commit does appear to reduce utilization when the window is not focused, but with a 500 ms timeout it's still enough to stand out. (Testing on a work desktop at the moment, so numbers are not comparable).

The proper solution involves converting core.run() itself to be event-based and cranked by SDL_WaitEvent, placing other event sources in SDL's event loop as necessary. The main issue would appear to be run_threads, which would need to be replaced by a task queue that wakes the loop when tasks are pushed.

**Comment by rxi** [comment] 2020-05-11 15:06
The 500ms timeout is intentional so minor background tasks can still continue to run, albeit at a trickle compared to when focused. If you feel it's still taking too many resources you can increase this timeout value on your local copy, likely with few-if-any practical negative consequences. I personally consider the behaviour to be acceptable and don't intend to change it any further, I don't feel the application should be restructured just to reduce an already fractional percentage of CPU usage.

**Comment by kennylevinsen** [comment] 2020-05-11 15:21
I hope it wasn't coming across as a strong criticism. It's still an improvement. I'm just on an eternal vendetta against idle utilization that isn't doing anything as it negatively affects battery life.

Would you be opposed to improvements here? If so, I might try to look into it myself.

**Comment by rxi** [comment] 2020-05-11 19:27
As a laptop user I'm on the same page and in agreement with the general idea of not wanting to burn through battery life unnecessarily, this primarily is why I made the changes I did in the first place. That being said I'm happy with the current structure of the thing and don't feel adding extra complexity is worth it, the amount of CPU usage we're talking here is tiny and realistically I doubt is having any practical negative effects on battery life.

**Comment by kennylevinsen** [comment] 2020-05-11 19:50
Looking at things, I suspect the situation might actually be fixable with very minor changes, maintaining run_threads and everything else pretty much as-is.

Progress is a little slower than I'd like due to never in my life having used Lua, but I might have something to show relatively soon.

**Comment by kennylevinsen** [comment] 2020-05-11 23:37
I have thrown something together over in https://github.com/kennylevinsen/lite/commit/5f3332149bd985db6802ad6de04dc8de2ec2a548.

The general idea is that View:update implementations can return a sleep target if they have future work (e.g. cursor blink). Combined with thread.wake, this allows calculating the appropriate sleep duration for a big SDL_WaitEvent, which will wake prematurely on user activity.

However, unfortunately I also fell over this little piece of SDL, which puts is putting a stick in the wheel for a full flat 0%: http://hg.libsdl.org/SDL/file/ccd76043c80e/src/events/SDL_events.c#l742. That is, SDL_WaitEvent is just `for(;;) { if(hasEvents()) return; usleep(1000); }`, instead of a poll with timeout as it should have been. Seems like SDL wasn't really targeting general purpose applications here, but only games.

I'll need to ponder some more.

**Comment by rxi** [comment] 2020-05-13 09:05
I'm not happy with the amount of changes this requires. The complexity added is completely disproportional compared to how much of a problem this actually is. We're talking *fractions* of a percentage, `lite` sits around the middle of other idle processes when I run `top` and reports `0%` CPU usage in windows task manager.

I'm in agreement with the base motivations ("don't waste resources") for wanting to further improve this, but from a practical standpoint I don't feel it's realistically a problem.

**Comment by kennylevinsen** [comment] 2020-05-13 11:33
Which part of the changes specifically are you unhappy with? I believe it would be more productive to discuss specific issues and possibly consider alternative solutions.

Windows task manager does not provide usable CPU load measures for sleeping loops like this. It doesn't show you the cost of the sleep at all. Linux CPU load measures show a more complete cost including kernel time, making them more representative (although of course not as good as profiling on any OS). I recall a cross platform code base from a decade ago that for the same loop showed 10-30% load on Linux and 0% on Windows.

I'm at 2-4% CPU idle on my laptop on master, which is quite significant. Note that the main issue for battery drain is not the cycle count, but that it causes wake ups, taking the CPU out of lower power states, keeping at awake for the minimum duration (these state changes take time).

However, if you're truly just entirely against additional work here, then I guess that's the unfortunate end of it. I'm only being stubborn because I like the project, and am considering throwing my current editor to the curb. :)

**Comment by rxi** [comment] 2020-05-17 09:39
lite is inevitably going to be using some processing power when idle to perform background tasks. As I said before I don't feel this is realistically an issue and isn't worth adding *any* additional complexity over. I feel the best solution for you to reduce the CPU usage on your personal instance would be by increasing that `500ms` timeout, but as you pointed out you'd still have the issue of how `SDL_WaitEventTimeout` works.

**Closed by rxi** 2020-05-17 09:39 UTC
