### ISSUE TITLE
[wayland] Segfault when  window is closed

### ISSUE THREAD

**Issue by kennylevinsen** [rxi/lite#74] opened 2020-05-10 17:19 UTC
Closing the the lite window with SDL in Wayland mode leads to a segfault. This does not happen under X11.

Run under a Wayland compositor with `SDL_VIDEODRIVER=wayland` to reproduce. Window is being closed under sway with the sway `kill` command, which is the normal way to whack a window, by default bound to `$mod+shift+q`.

Backtrace:
```
[kenny@lappy lite]$ ./lite
Segmentation fault (core dumped)
[kenny@lappy lite]$ coredumpctl debug
           PID: 29147 (lite)
           UID: 1000 (kenny)
           GID: 1000 (kenny)
        Signal: 11 (SEGV)
     Timestamp: Sun 2020-05-10 19:16:54 CEST (4s ago)
  Command Line: ./lite
    Executable: /home/kenny/src/github.com/rxi/lite/lite
 Control Group: /user.slice/user-1000.slice/session-3.scope
          Unit: session-3.scope
         Slice: user-1000.slice
       Session: 3
     Owner UID: 1000 (kenny)
       Boot ID: d8c9c67d39814978bab656c93a20a32d
    Machine ID: 97f9d58f7c3743ecb7fcbeccaa616aa1
      Hostname: lappy
       Storage: /var/lib/systemd/coredump/core.lite.1000.d8c9c67d39814978bab656c93a20a32d.29147.1589131014000000000000.lz4
       Message: Process 29147 (lite) of user 1000 dumped core.

                Stack trace of thread 29147:
                #0  0x00007efc49df70ac malloc_consolidate (libc.so.6 + 0x870ac)
                #1  0x00007efc49df8600 _int_free (libc.so.6 + 0x88600)
                #2  0x00007efc4a0ead6f n/a (libSDL2-2.0.so.0 + 0x6ed6f)
                #3  0x00007efc4a0c785a n/a (libSDL2-2.0.so.0 + 0x4b85a)
                #4  0x00007efc4a0c3a66 n/a (libSDL2-2.0.so.0 + 0x47a66)
                #5  0x00007efc4a127999 n/a (libSDL2-2.0.so.0 + 0xab999)
                #6  0x00007efc4a12bbbb n/a (libSDL2-2.0.so.0 + 0xafbbb)
                #7  0x00007efc4a12bf45 n/a (libSDL2-2.0.so.0 + 0xaff45)
                #8  0x00007efc4a0995cb n/a (libSDL2-2.0.so.0 + 0x1d5cb)
                #9  0x00007efc4a0996b8 n/a (libSDL2-2.0.so.0 + 0x1d6b8)
                #10 0x00007efc49dae537 __run_exit_handlers (libc.so.6 + 0x3e537)
                #11 0x00007efc49dae6ee exit (libc.so.6 + 0x3e6ee)
                #12 0x00005585f88d62d1 n/a (/home/kenny/src/github.com/rxi/lite/lite + 0x202d1)

GNU gdb (GDB) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/kenny/src/github.com/rxi/lite/lite...
[New LWP 29147]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `./lite'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007efc49df70ac in malloc_consolidate () from /usr/lib/libc.so.6
(gdb) bt full
#0  0x00007efc49df70ac in malloc_consolidate () from /usr/lib/libc.so.6
No symbol table info available.
#1  0x00007efc49df8600 in _int_free () from /usr/lib/libc.so.6
No symbol table info available.
#2  0x00007efc4a0ead6f in ?? () from /usr/lib/libSDL2-2.0.so.0
No symbol table info available.
#3  0x00007efc4a0c785a in ?? () from /usr/lib/libSDL2-2.0.so.0
No symbol table info available.
#4  0x00007efc4a0c3a66 in ?? () from /usr/lib/libSDL2-2.0.so.0
No symbol table info available.
#5  0x00007efc4a127999 in ?? () from /usr/lib/libSDL2-2.0.so.0
No symbol table info available.
#6  0x00007efc4a12bbbb in ?? () from /usr/lib/libSDL2-2.0.so.0
No symbol table info available.
#7  0x00007efc4a12bf45 in ?? () from /usr/lib/libSDL2-2.0.so.0
No symbol table info available.
#8  0x00007efc4a0995cb in ?? () from /usr/lib/libSDL2-2.0.so.0
No symbol table info available.
#9  0x00007efc4a0996b8 in ?? () from /usr/lib/libSDL2-2.0.so.0
No symbol table info available.
#10 0x00007efc49dae537 in __run_exit_handlers () from /usr/lib/libc.so.6
No symbol table info available.
#11 0x00007efc49dae6ee in exit () from /usr/lib/libc.so.6
No symbol table info available.
#12 0x00005585f88d62d1 in os_exit (L=0x5585f93ba040) at src/lib/lua52/loslib.c:295
        status = 0
#13 0x00005585f88cc156 in luaD_precall (L=L@entry=0x5585f93ba040, func=<optimized out>, func@entry=0x5585f9b3fb60, nresults=nresults@entry=0) at src/lib/lua52/ldo.c:319
        f = 0x5585f88d6250 <os_exit>
        ci = <optimized out>
        n = <optimized out>
        funcr = <optimized out>
#14 0x00005585f88e2a57 in luaV_execute (L=L@entry=0x5585f93ba040) at src/lib/lua52/lvm.c:709
        b = <optimized out>
        nresults = 0
        i = <optimized out>
        ra = 0x5585f9b3fb60
        a = <optimized out>
        ci = <optimized out>
        cl = 0x5585f9a3b430
        k = 0x5585f9a19ce0
        base = <optimized out>
#15 0x00005585f88cc6e8 in luaD_call (L=0x5585f93ba040, func=<optimized out>, nResults=<optimized out>, allowyield=<optimized out>) at src/lib/lua52/ldo.c:402
No locals.
#16 0x00005585f88cba3c in luaD_rawrunprotected (L=0x5585f93ba040, f=0x5585f88bded0 <f_call>, ud=0x7fff81b5b740) at src/lib/lua52/ldo.c:131
        oldnCcalls = 2
        lj = {previous = 0x7fff81b5b8e0, b = {{__jmpbuf = {94033900445760, 883511880359127535, 96, 94033907974032, 1, 1000000, -883305634149914129, -6392529513830110737},
              __mask_was_saved = 0, __saved_mask = {__val = {94033898357568, 140733193388032, 1, 4179346264, 94033898357360, 0, 12884901891, 94033889047551, 0,
                  94033900445968, 48, 40, 0, 94033900445760, 94033900445760, 0}}}}, status = 0}
#17 0x00005585f88cca93 in luaD_pcall (L=L@entry=0x5585f93ba040, func=func@entry=0x5585f88bded0 <f_call>, u=u@entry=0x7fff81b5b740, old_top=512, ef=<optimized out>) at src/lib/lua52/ldo.c:603
        status = <optimized out>
        old_ci = 0x5585f9ae7f90
        old_allowhooks = 1 '\001'
        old_nny = 3
        old_errfunc = 96
#18 0x00005585f88c0e13 in lua_pcallk (L=L@entry=0x5585f93ba040, nargs=nargs@entry=5, nresults=nresults@entry=-1, errfunc=errfunc@entry=1, ctx=ctx@entry=0, k=k@entry=0x5585f88c5070 <pcallcont>) at src/lib/lua52/lapi.c:949
        c = {func = 0x5585f9b3fa10, nresults = -1}
        status = <optimized out>
        func = <optimized out>
#19 0x00005585f88c4ab5 in luaB_xpcall (L=0x5585f93ba040) at src/lib/lua52/lbaselib.c:405
        status = <optimized out>
        n = 7
#20 0x00005585f88cc156 in luaD_precall (L=L@entry=0x5585f93ba040, func=<optimized out>, func@entry=0x5585f9b3f9f0, nresults=nresults@entry=2) at src/lib/lua52/ldo.c:319
        f = 0x5585f88c4a50 <luaB_xpcall>
        ci = <optimized out>
        n = <optimized out>
        funcr = <optimized out>
#21 0x00005585f88e2a57 in luaV_execute (L=L@entry=0x5585f93ba040) at src/lib/lua52/lvm.c:709
        b = <optimized out>
        nresults = 2
        i = <optimized out>
        ra = 0x5585f9b3f9f0
        a = <optimized out>
        ci = <optimized out>
        cl = 0x5585f9a3ba10
        k = 0x5585f9a209b0
        base = <optimized out>
#22 0x00005585f88cc6e8 in luaD_call (L=0x5585f93ba040, func=<optimized out>, nResults=<optimized out>, allowyield=<optimized out>) at src/lib/lua52/ldo.c:402
No locals.
#23 0x00005585f88cba3c in luaD_rawrunprotected (L=0x5585f93ba040, f=0x5585f88bded0 <f_call>, ud=0x7fff81b5ba20) at src/lib/lua52/ldo.c:131
        oldnCcalls = 1
        lj = {previous = 0x7fff81b5bbc0, b = {{__jmpbuf = {94033900445760, 883511880285727215, 0, 94033907087616, 1, 1000000, -883305633986336273, -6392529513830110737}, __mask_was_saved = 0, __saved_mask = {__val = {140735369558496, 94033889044558, 15, 94033907016384, 140735369559032, 0, 4, 1099511627776, 7, 390842023936, 64, 48, 94033907016384, 94033907084432, 0, 1}}}}, status = 0}
#24 0x00005585f88cca93 in luaD_pcall (L=L@entry=0x5585f93ba040, func=func@entry=0x5585f88bded0 <f_call>, u=u@entry=0x7fff81b5ba20, old_top=112, ef=<optimized out>) at src/lib/lua52/ldo.c:603
        status = <optimized out>
        old_ci = 0x5585f9a0f900
        old_allowhooks = 1 '\001'
        old_nny = 2
        old_errfunc = 0
#25 0x00005585f88c0e13 in lua_pcallk (L=L@entry=0x5585f93ba040, nargs=nargs@entry=0, nresults=nresults@entry=-1, errfunc=errfunc@entry=1, ctx=ctx@entry=0, k=k@entry=0x5585f88c5070 <pcallcont>) at src/lib/lua52/lapi.c:949
        c = {func = 0x5585f91d4cb0, nresults = -1}
        status = <optimized out>
        func = <optimized out>
#26 0x00005585f88c4ab5 in luaB_xpcall (L=0x5585f93ba040) at src/lib/lua52/lbaselib.c:405
        status = <optimized out>
        n = 2
#27 0x00005585f88cc156 in luaD_precall (L=L@entry=0x5585f93ba040, func=<optimized out>, func@entry=0x5585f91d4c90, nresults=nresults@entry=0) at src/lib/lua52/ldo.c:319
        f = 0x5585f88c4a50 <luaB_xpcall>
        ci = <optimized out>
        n = <optimized out>
        funcr = <optimized out>
#28 0x00005585f88e2a57 in luaV_execute (L=L@entry=0x5585f93ba040) at src/lib/lua52/lvm.c:709
        b = <optimized out>
        nresults = 0
        i = <optimized out>
        ra = 0x5585f91d4c90
        a = <optimized out>
        ci = <optimized out>
        cl = 0x5585f9a0ec00
        k = 0x5585f99fb190
        base = <optimized out>
#29 0x00005585f88cc6e8 in luaD_call (L=0x5585f93ba040, func=<optimized out>, nResults=<optimized out>, allowyield=<optimized out>) at src/lib/lua52/ldo.c:402
No locals.
#30 0x00005585f88cba3c in luaD_rawrunprotected (L=0x5585f93ba040, f=0x5585f88bded0 <f_call>, ud=0x7fff81b5bd00) at src/lib/lua52/ldo.c:131
        oldnCcalls = 0
        lj = {previous = 0x0, b = {{__jmpbuf = {94033900445760, 883511880294115823, 0, 94033900445888, 1, 0, -883305633940198929, -6392529513830110737}, __mask_was_saved = 0, __saved_mask = {__val = {94033907004320, 17179869184, 0, 0, 0, 0, 0, 94033889180408, 0, 8411342524095865344, 94033900445968, 0, 94033900445760, 94033889180408, 0, 8411342524095865344}}}}, status = 0}
#31 0x00005585f88cca93 in luaD_pcall (L=L@entry=0x5585f93ba040, func=func@entry=0x5585f88bded0 <f_call>, u=u@entry=0x7fff81b5bd00, old_top=48, ef=<optimized out>) at src/lib/lua52/ldo.c:603
        status = <optimized out>
        old_ci = 0x5585f93ba0c0
        old_allowhooks = 1 '\001'
        old_nny = 1
        old_errfunc = 0
#32 0x00005585f88c0e13 in lua_pcallk (L=0x5585f93ba040, nargs=<optimized out>, nresults=-1, errfunc=<optimized out>, ctx=<optimized out>, k=<optimized out>) at src/lib/lua52/lapi.c:949
        c = {func = 0x5585f91d4c70, nresults = -1}
        status = <optimized out>
        func = <optimized out>
#33 0x00005585f88bcb7c in main (argc=<optimized out>, argv=<optimized out>) at src/main.c:50
        dm = {format = 370546692, w = 3840, h = 2160, refresh_rate = 59, driverdata = 0x5585f91c3500}
        L = 0x5585f93ba040
        exedir = "/home/kenny/src/github.com/rxi/lite\000lite\000.\036J\374~\000\000p\277\265\201\377\177\000\000\003\"!J\374~\000\000\001\000\000\000\000\000\000\000\360)\036J\374~\000\000\220\277\265\201\377\177\000\000\003\"!J\374~\000\000\001\000\000\000\000\000\000\000\000%\036J\374~\000\000\260\277\265\201\377\177\000\000\003\"!J\374~\000\000\001\000\000\000\000\000\000\000\000 \036J\374~\000\000п\265\201\377\177\000\000\003\"!J\374~\000\000\001\000\000\000\000\000\000\000 \001#J\374~\000\000\360\277\265\201\377\177", '\000' <repeats 50 times>...
```

**Comment by rxi** [comment] 2020-05-29 09:57
Closing as this is a duplicate of #53

**Closed by rxi** 2020-05-29 09:57 UTC
