### ISSUE TITLE
View hidden files in tree view

### ISSUE THREAD

**Issue by harikt** [rxi/lite#102] opened 2020-05-16 06:59 UTC
I noticed not all files are shown in tree view. Eg `.env` .

So files starting with `.` should also be shown.

**Comment by rxi** [comment] 2020-05-17 09:25
Currently the treeview lists all the files from `core.project_files` which ignores files beginning with `.`, if the treeview's shown files change in the future it will be a result of lite populating `core.project_files` differently.

As this issue is also concerned with how lite goes about ignoring certain project files, I'm considering a duplicate of #77

**Closed by rxi** 2020-05-17 09:25 UTC

**Comment by harikt** [comment] 2020-05-18 05:58
So is there a way we can see hidden files. Some sort of config values we can put in `data/user/init.lua`?

**Comment by vallode** [comment] 2021-03-07 13:51
> So is there a way we can see hidden files. Some sort of config values we can put in `data/user/init.lua`?

Just putting it here in case others find this: 
* Open up `init.lua` (Your lite config file).
* Add `config.ignore_files = "a^"`
* _All_ files should now show up in your tree view.

Could not figure out a better way but this works rather fine :)
