### ISSUE TITLE
Text is blurry on macOS

### ISSUE THREAD

**Issue by bioglaze** [rxi/lite#162] opened 2020-06-23 09:48 UTC
Text is blurry on macOS, tested on Lite 1.09 macOS build by @gingerbeardman. I wonder if Retina/HiDPI support hasn't been enabled in the .plist file or something? I'm using macOS Mojave, Retina MacBook Pro 2013, font smoothing disabled. Attached a comparison image with Xcode/Lite:

![xcode_vs_lite](https://user-images.githubusercontent.com/7099779/85389141-b7dd5100-b54f-11ea-8542-0c05adb01741.png)

**Comment by gingerbeardman** [comment] 2020-06-23 09:52
From my macOS build thread:

> - [see other issues](https://github.com/rxi/lite/search?q=mac&type=Issues) for outstanding problems on macOS

**Comment by rxi** [comment] 2020-06-23 12:44
Closing as a duplicate of https://github.com/rxi/lite/issues/46

**Closed by rxi** 2020-06-23 12:44 UTC
